import { createFileRoute,Link } from "@tanstack/react-router";import { useEffect,useRef,useState } from "react";import { Loader2 } from "lucide-react";import { Button } from "@/components/ui/button";import { copy } from "@/data/store";import { useCartDetails,useStore } from "@/state/storefront";import { createShopifyCheckout } from "@/lib/shopify";
export const Route=createFileRoute("/checkout")({head:()=>({meta:[{title:"Checkout — ASSEL KRUSZKA"},{name:"description",content:"Complete your ASSEL KRUSZKA order."},{property:"og:title",content:"Checkout — ASSEL KRUSZKA"},{property:"og:description",content:"Complete your ASSEL KRUSZKA order."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Page});
// This route no longer collects payment itself — it hands the cart straight
// to Shopify's own hosted checkout (real tax/shipping calculation, and
// whichever payment methods are enabled in Shopify Settings → Payments).
function Page(){const st=useStore(),items=useCartDetails(),t=copy[st.locale];const[failed,setFailed]=useState(false);const started=useRef(false);
useEffect(()=>{if(started.current||items.length===0)return;const lines=items.map(({line})=>line.variantId?{variantId:line.variantId,quantity:line.quantity}:null).filter((l):l is{variantId:string;quantity:number}=>l!==null);if(lines.length===0){setFailed(true);return}started.current=true;createShopifyCheckout(lines).then(url=>{if(url)window.location.href=url;else setFailed(true)})},[items]);
if(failed)return <main className="page-wrap text-center"><h1 className="mt-6 font-display text-4xl">{t.checkoutErrorTitle}</h1><p className="mt-4 text-muted-foreground">{t.checkoutErrorText}</p><Button asChild className="mt-8"><Link to="/cart">{t.bag}</Link></Button></main>;
if(items.length===0)return <main className="page-wrap text-center"><p className="text-muted-foreground">{t.cartEmptyCheckout}</p><Button asChild className="mt-6"><Link to="/catalog" search={{category:"all",q:""}}>{t.shop}</Link></Button></main>;
return <main className="page-wrap text-center"><Loader2 className="mx-auto size-8 animate-spin text-primary"/><p className="mt-4 text-muted-foreground">{t.redirectingCheckout}</p></main>}
